from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from fake_useragent import UserAgent
import time
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.bing.com/videos/search?q=XO+Team+-+%22xo+team%22+best+tiktok+compilation+(part+7)&docid=607992662944188901&mid=945EC01C53F2B0670842945EC01C53F2B0670842&view=detail&FORM=VIRE')
time.sleep(180)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3683.90 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjDiqmI6JP1AhXfgv0HHUvLCFEQtwJ6BAgHEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yjr&usg=AOvVaw077SfyiujAb-CaM4q9CKWy')
time.sleep(195)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3683.90 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwi8kKGr6JP1AhURh_0HHZCzBJYQtwJ6BAgJEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yp0&usg=AOvVaw1W2u-nLakx5ZHrDdmoLark')
time.sleep(206)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/12.0.0 Mobile/15A5370a Safari/602.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj29Ky-6JP1AhVL8LsIHQ_yAvgQtwJ6BAgJEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yjp&usg=AOvVaw34LaOGy_U4d706dnrf2AdG')
time.sleep(190)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3683.90 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjRguzu6JP1AhVQgf0HHUHmDi44FBC3AnoECA4QAg&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yp4&usg=AOvVaw1QcsEI0n0Z1eGcPasBUuXC')
time.sleep(220)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3683.90 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj2tJzL6JP1AhUfiv0HHUI2BfgQtwJ6BAgKEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yp3&usg=AOvVaw0dzz1tMElrL-bWOPRrT-nq')
time.sleep(320)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 10; OnePlus Nord) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.120 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwj29Ky-6JP1AhVL8LsIHQ_yAvgQtwJ6BAgJEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yjp&usg=AOvVaw34LaOGy_U4d706dnrf2AdG')
time.sleep(280)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-F700U/DS Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3396.87 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&cad=rja&uact=8&ved=2ahUKEwi5seCjo5H1AhVojIkEHVLrD7oQuAJ6BAgIEAc&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yjq&usg=AOvVaw0Bl5GVHofQiIlT0o9qTx5n')
time.sleep(150)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 12; SM-G998B Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3396.87 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://t.co/2XpvbW4LN4')
time.sleep(230)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/11.0.0 Mobile/15A5370a Safari/602.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.bing.com/videos/search?q=XO+Team+-+%22xo+team%22+best+tiktok+compilation+(part+7)&docid=607992662944188901&mid=945EC01C53F2B0670842945EC01C53F2B0670842&view=detail&FORM=VIRE')
time.sleep(270)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 12_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/12.0.0 Mobile/15A5370a Safari/602.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiph7W445P1AhVpn-AKHWh7C5kQtwJ6BAgDEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fplaylist%2Fx7c2rc&usg=AOvVaw2jE3x60yyMyTNOXRle8zn_')
time.sleep(300)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/14.0.0 Mobile/15A5370a Safari/602.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=video&cd=&cad=rja&uact=8&ved=2ahUKEwi5seCjo5H1AhVojIkEHVLrD7oQuAJ6BAgIEAc&url=https%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx866yjq&usg=AOvVaw0Bl5GVHofQiIlT0o9qTx5n')
time.sleep(260)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; SM-T970) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3282.137 Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://t.co/ZCqZK38WxU')
time.sleep(220)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; SM-T970) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3282.137 Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwivtMfo4JP1AhXQlIkEHYjYCZoQFnoECAMQAQ&url=https%3A%2F%2Fwww.dailymotion.com%2Ftopshortsvideo%2Fplaylists&usg=AOvVaw3Xzo_dGMmjouJ13Q0MIDDb')
time.sleep(233)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-F700U/DS Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3396.87 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiph7W445P1AhVpn-AKHWh7C5kQtwJ6BAgDEAI&url=https%3A%2F%2Fwww.dailymotion.com%2Fplaylist%2Fx7c2rc&usg=AOvVaw2jE3x60yyMyTNOXRle8zn')
time.sleep(266)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G980F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3396.87 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.bing.com/videos/search?q=XO+Team+-+%22xo+team%22+best+tiktok+compilation+(part+7)&docid=607992662944188901&mid=945EC01C53F2B0670842945EC01C53F2B0670842&view=detail&FORM=VIRE')
time.sleep(270)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G980F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3396.87 Mobile Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.bing.com/videos/search?q=XO+Team+-+%22xo+team%22+best+tiktok+compilation+(part+7)&docid=607992662944188901&mid=945EC01C53F2B0670842945EC01C53F2B0670842&view=detail&FORM=VIRE')
time.sleep(280)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/14.0.0 Mobile/15A5370a Safari/602.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwivtMfo4JP1AhXQlIkEHYjYCZoQFnoECAMQAQ&url=https%3A%2F%2Fwww.dailymotion.com%2Ftopshortsvideo%2Fplaylists&usg=AOvVaw3Xzo_dGMmjouJ13Q0MIDDb')
time.sleep(198)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 14_0 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/12.0.0 Mobile/15A5370a Safari/602.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://t.co/2XpvbW4LN4')
time.sleep(125)
driver.quit()
options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (iPad; CPU OS 14_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/14.0 Mobile/15A5341f Safari/604.1')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('https://t.co/2XpvbW4LN4')
time.sleep(155)
driver.quit()

options = Options()
ua = UserAgent()
userAgent = ua.random
print(userAgent)
options.add_argument(f'user-agent=Mozilla/5.0 (Linux; Android 11; SM-T970) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.3282.137 Safari/537.36')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'./chromedriver')
driver.get('')
time.sleep(169)
driver.quit()
